/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recommendations */
        get: operations["recommendations_recommendations__userId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Rating
         * @description specs/rating-ingestion-api/spec.md "Submit a rating over HTTP" +
         *     "API-side validation before publishing" + "202 means durably accepted, not
         *     applied". Validation order matches design.md/tasks.md 1.5: userId, rating,
         *     movieId, then eventId — all 422s happen before anything touches Kafka.
         */
        post: operations["submit_rating_ratings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ratings/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rating Status
         * @description specs/rating-ingestion-api/spec.md "Rating status lookup". `rating_events`
         *     only holds an eventId after serve_batch has applied it (pipeline.py: ledger
         *     insert happens after effects), so absence means pending, not unknown.
         */
        get: operations["rating_status_ratings__eventId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug User
         * @description specs/demo-web-client/spec.md "Debug state endpoint" — demo-only, 404 when
         *     `api.demo_enabled` is false (spec: "Disabled in production").
         */
        get: operations["debug_user_debug_users__userId__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Movies
         * @description specs/movie-catalog/spec.md "Movie list and search endpoint": demo-only (404 before any parameter is checked). The average rating and
         *     WR are the training-split numbers plus the ratings applied since, the same as the popular list; without a baseline they are null and only
         *     sorting by `title` or `ratings` is possible.
         */
        get: operations["list_movies_movies_get"];
        put?: never;
        /**
         * Create Movie
         * @description specs/new-movie-cold-start/spec.md "Create a demo movie". The movie goes only into
         *     MongoDB (design D-10): it is a demo shortcut, not a catalog ETL.
         */
        post: operations["create_movie_movies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/movies/{movieId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Movie
         * @description Only the reserved demo range can be deleted, so the MovieLens catalog is protected.
         *     Ratings already given to the movie stay in user_rated.
         */
        delete: operations["delete_movie_movies__movieId__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug System
         * @description specs/demo-case-scenarios/spec.md "Model lifecycle and retrain progress view" — read
         *     only: nothing here starts retraining or changes the active version.
         */
        get: operations["debug_system_debug_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/debug/popularity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Popularity
         * @description specs/demo-popularity-live/spec.md "Popularity debug endpoint": the numbers behind the popular list a new user
         *     receives. `m` is a what-if (serving keeps the configured value); `deltas=false` ignores the ledger. Works whether or
         *     not `popularity.live` is on (`liveEnabled` says which list /recommendations uses); without a usable baseline it shows
         *     the artifact list.
         */
        get: operations["debug_popularity_debug_popularity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Ratings
         * @description specs/user-rating-history-api/spec.md — what a user rated most recently. Like
         *     /debug/users it exposes viewing history by userId, so it is demo-only.
         */
        get: operations["user_ratings_users__userId__ratings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DebugPipelineOut */
        DebugPipelineOut: {
            /** Lastbatchid */
            lastBatchId: number | null;
            /** Lastrunat */
            lastRunAt: string | null;
        };
        /**
         * DebugUserOut
         * @description GET /debug/users/{userId} — demo-only (specs/demo-web-client/spec.md
         *     "Debug state endpoint"). Field names mirror the Mongo documents directly
         *     (interaction_count, recent_movieIds, ...) rather than the recommendations
         *     response's camelCase, since this endpoint exists to show "what's actually
         *     stored", not a client-facing contract.
         */
        DebugUserOut: {
            /** Userid */
            userId: number;
            /** Interaction Count */
            interaction_count: number;
            /** Recent Movieids */
            recent_movieIds: number[];
            /** Positive Movieids */
            positive_movieIds: number[];
            /** Lastupdated */
            lastUpdated: string | null;
            pipeline: components["schemas"]["DebugPipelineOut"];
            /** Modelversion */
            modelVersion: string;
        };
        /** DemoMovieOut */
        DemoMovieOut: {
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string[];
            /** Addedat */
            addedAt: string | null;
        };
        /** DemoSettingsOut */
        DemoSettingsOut: {
            /** Ratingpolltimeoutseconds */
            ratingPollTimeoutSeconds: number;
            /** Newitemsenabled */
            newItemsEnabled: boolean;
            /** Demomovieidstart */
            demoMovieIdStart: number;
            /** Tierthreshold */
            tierThreshold: number;
        };
        /** GateCheckOut */
        GateCheckOut: {
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ModelVersionOut */
        ModelVersionOut: {
            /** Version */
            version: string;
            /** Status */
            status: string;
            /** Importedat */
            importedAt: string | null;
            /** Activatedat */
            activatedAt: string | null;
            /** Gatechecks */
            gateChecks: components["schemas"]["GateCheckOut"][];
        };
        /** MovieCreated */
        MovieCreated: {
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string[];
            /** Addedat */
            addedAt: string;
        };
        /**
         * MovieIn
         * @description POST /movies body (specs/new-movie-cold-start/spec.md "Create a demo movie").
         */
        MovieIn: {
            /** Title */
            title: string;
            /** Genres */
            genres: string[];
        };
        /** MovieListOut */
        MovieListOut: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
            /** Pages */
            pages: number;
            /** Hasstats */
            hasStats: boolean;
            /** M */
            m: number;
            /** C */
            c: number | null;
            /** Items */
            items: components["schemas"]["MovieRowOut"][];
        };
        /**
         * MovieRowOut
         * @description One row of GET /movies.
         */
        MovieRowOut: {
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string[];
            /** Ratings */
            ratings: number;
            /** Trainratings */
            trainRatings: number;
            /** Newratings */
            newRatings: number;
            /** Avgrating */
            avgRating: number | null;
            /** Wr */
            wr: number | null;
            /** Isdemo */
            isDemo: boolean;
        };
        /** PopularityBaselineOut */
        PopularityBaselineOut: {
            /** Generatedat */
            generatedAt: string;
            /** Cutoff */
            cutoff: number;
            /** Ratings */
            ratings: number;
        };
        /**
         * PopularityItemOut
         * @description One row of GET /debug/popularity: the numbers behind a movie's weighted rating.
         */
        PopularityItemOut: {
            /** Rank */
            rank: number;
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string;
            /** Avgrating */
            avgRating: number | null;
            /** Support */
            support: number;
            /** Basesupport */
            baseSupport: number;
            /** Newratings */
            newRatings: number;
            /** Wr */
            wr: number;
            /** Baserank */
            baseRank: number | null;
        };
        /** PopularityOut */
        PopularityOut: {
            /** Source */
            source: string;
            /** Liveenabled */
            liveEnabled: boolean;
            /** Preview */
            preview: boolean;
            /** M */
            m: number;
            /** C */
            c: number | null;
            /** Minsupport */
            minSupport: number;
            baseline: components["schemas"]["PopularityBaselineOut"] | null;
            /** Appliedevents */
            appliedEvents: number;
            /** Generatedat */
            generatedAt: string;
            /** Items */
            items: components["schemas"]["PopularityItemOut"][];
        };
        /** RatedMovieOut */
        RatedMovieOut: {
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string;
            /** Rating */
            rating: number | null;
            /** Incatalog */
            inCatalog: boolean;
        };
        /** RatingAccepted */
        RatingAccepted: {
            /** Eventid */
            eventId: string;
            /**
             * Status
             * @default accepted
             */
            status: string;
        };
        /**
         * RatingHistoryOut
         * @description GET /users/{userId}/ratings (specs/user-rating-history-api/spec.md).
         */
        RatingHistoryOut: {
            /** Userid */
            userId: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["RatedMovieOut"][];
        };
        /**
         * RatingIn
         * @description POST /ratings body (specs/rating-ingestion-api/spec.md "Submit a rating over
         *     HTTP"). `eventId` is optional: omitted -> server generates a UUID4 (D-5);
         *     supplied -> used as-is for idempotency, so a retried request applies at most
         *     once downstream.
         */
        RatingIn: {
            /** Userid */
            userId: number;
            /** Movieid */
            movieId: number;
            /** Rating */
            rating: number;
            /** Eventid */
            eventId?: string | null;
        };
        /** RatingStatus */
        RatingStatus: {
            /** Eventid */
            eventId: string;
            /** Status */
            status: string;
            /** Batchid */
            batchId?: number | null;
            /** Ingestedat */
            ingestedAt?: string | null;
        };
        /** RecommendationItemOut */
        RecommendationItemOut: {
            /** Movieid */
            movieId: number;
            /** Title */
            title: string;
            /** Genres */
            genres: string;
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            /** Source */
            source: string;
        };
        /** RecommendationResponseOut */
        RecommendationResponseOut: {
            /** Userid */
            userId: number;
            /** Tier */
            tier: string;
            /** Strategy */
            strategy: string;
            /** Modelversion */
            modelVersion: string;
            /** Generatedat */
            generatedAt: string;
            /** Fallbackreason */
            fallbackReason: string | null;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItemOut"][];
        };
        /** RetrainProgressOut */
        RetrainProgressOut: {
            /** Pending */
            pending: number;
            /** Nmin */
            nMin: number;
            /** Watermark */
            watermark: string | null;
        };
        /**
         * SystemStatusOut
         * @description GET /debug/system — read-only view of the model lifecycle for use cases 5 and 6,
         *     plus the demo movies the page lets the presenter delete.
         */
        SystemStatusOut: {
            /** Activeversion */
            activeVersion: string;
            /** Versions */
            versions: components["schemas"]["ModelVersionOut"][];
            retrainProgress: components["schemas"]["RetrainProgressOut"];
            demo: components["schemas"]["DemoSettingsOut"];
            /** Demomovies */
            demoMovies: components["schemas"]["DemoMovieOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    recommendations_recommendations__userId__get: {
        parameters: {
            query?: {
                k?: number;
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponseOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_rating_ratings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rating_status_ratings__eventId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_user_debug_users__userId__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movies_movies_get: {
        parameters: {
            query?: {
                /** @description words of the title; every one must occur, any letter case */
                q?: string;
                /** @description one MovieLens genre, any letter case */
                genre?: string | null;
                sort?: "title" | "ratings" | "avg" | "wr";
                /** @description default asc for title, desc otherwise */
                order?: ("asc" | "desc") | null;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_movie_movies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovieIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovieCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_movie_movies__movieId__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                movieId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_system_debug_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusOut"];
                };
            };
        };
    };
    debug_popularity_debug_popularity_get: {
        parameters: {
            query?: {
                n?: number;
                m?: number | null;
                deltas?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopularityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_ratings_users__userId__ratings_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingHistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
